# Generated by Django 4.2.1 on 2023-09-24 04:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conversation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversationmessage",
            old_name="Conversation",
            new_name="conversation",
        ),
    ]
